### ISSUE TITLE
Gravity for player and pixels

### ISSUE THREAD

**Issue by korysanchez** [jkruse7/cs1666_pixelstellar#26]
Create a gravity force, which is a trait that can be inherited by the player, and any pixel elements. should mostly match real gravity, i.e. will accelerate towards 9.8 m/s.

**Comment by Chisato243** [comment]
1m = ??? pixels

**Comment by korysanchez** [comment]
lets say 1 for now

**Comment by korysanchez** [comment]
The calculations for gravity are done in the player file, but we should abstract the calculations to be done in the gravity.rs file. We'll leave this to a future date however, as it's currently functional for the player.

**Comment by korysanchez** [comment]
good enough for now, but may need some work in the future. well see how it goes when implementing.
